steps:
  - name: 'arico/python36'
    args: ['tox','--','-x','main_test.py']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['gcloud','functions','deploy','hello_get','--runtime','python37','--trigger-http','--region','europe-west-1']
    env: ['CLOUDSDK_COMPUTE_ZONE=europe-west1']